title: Taiming Kang | Academic Homepage
page-top-title: Taiming Kang
top-section-bg-text: Computer Science
home-subtitle: Taiming Kang&ensp;|&ensp;康泰铭
copyright-text: '&copy; Taiming Kang 2026. Website content licensed separately unless otherwise noted.'
