title: Taiming Kang's Homepage
page-top-title: Taiming Kang
top-section-bg-text: Computer Science
home-subtitle: Taiming Kang&ensp;|&ensp;康泰铭
copyright-text: '&copy; Taiming Kang 2023-2026. All Rights Reserved.'
